### ISSUE TITLE
Discuss Nix/NixOS on Mac in '`001-RandomDSdevel-Thoughts-on-an-Ideal-Personal-Package-Management-Workflow.md`' Or Some Other Document

### ISSUE THREAD

**Issue by rw** [portage-brew/portage-brew-staging-and-evolution#5] opened 2019-01-16 18:31 UTC
https://nixos.org/nix/

**Comment by RandomDSdevel** [comment] 2019-01-17 03:41
@rw:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Closed as a duplicate of #2; folding discussion into that thread.  (See [this comment](https://github.com/portage-brew/portage-brew/issues/2#issuecomment-455031342) in particular.)

**Comment by rw** [comment] 2019-01-17 04:10
@RandomDSdevel My intention was for a discussion of Nix to be placed in the README along with the other package managers.

**Comment by RandomDSdevel** [comment] 2019-01-17 04:18
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK, sorry.  Feel free to beat me to adding this by submitting a PR; I wouldn't get to adding more than the same link you started this thread with in tonight, anyway, and _that's_ not much of a discussion, now, _is_ it?

**Comment by RandomDSdevel** [comment] 2019-01-26 01:38
@rw:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm renaming this issue to reflect the merger of #9.

**Closed as completed** 2021-11-05 00:09 UTC
